#!/usr/bin/env bash

# Source the formatting functions
source "$(dirname "$0")/bash_utilities"

# Define an array of source directories
SOURCE_DIRS=("$HOME/Documents" "$HOME/Pictures")
EXCLUDES=("/github-fmc**" "/git-misc**" "/github-uphill**")

# Define the remote location (update this to match your actual remote name)
REMOTE="GoogleDrive:HomeBackup"

# Define the log file with a timestamp
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
LOG_FILE="$HOME/.log/cron/rclone-drive-backup_$TIMESTAMP.log"

# Create the log directory if it doesn't exist
mkdir -p "$(dirname "$LOG_FILE")"

# Inform about the beginning of the backup process
printf "${BLUE}$(date)${NC}: Starting backup process...${ENDL}"
printf "Log file: ${CYAN}$LOG_FILE${NC}${ENDL}"

# Loop through each directory in the array and sync it to the remote
for DIR in "${SOURCE_DIRS[@]}"; do
  DIR_NAME=$(basename "$DIR")

  # Build the exclude parameters for rclone
  EXCLUDE_PARAMS=()
  for EXCLUDE in "${EXCLUDES[@]}"; do
    EXCLUDE_PARAMS+=(--exclude "$EXCLUDE")
  done

  # Display the start of the sync operation in the terminal and log file
  printf "${BLUE}$(date)${NC}: Syncing ${YELLOW}$DIR_NAME${NC} to ${GREEN}$REMOTE${NC}...${ENDL}"
  printf "$(date): Starting sync of $DIR_NAME to ${GREEN}Google Drive${NC}${ENDL}" >> "$LOG_FILE"

  # Perform the sync operation with exclusions
  rclone sync "$DIR" "$REMOTE/$DIR_NAME" "${EXCLUDE_PARAMS[@]}" --log-file="$LOG_FILE" --log-level INFO

  # Display the completion of the sync operation in the terminal and log file
  printf "${BLUE}$(date)${NC}:${GREEN} Completed sync of $DIR_NAME to Google Drive${ENDL}"
  printf "$(date): Completed sync of $DIR_NAME${ENDL}" >> "$LOG_FILE"
done

# Inform about the completion of the backup process
printf "${GREEN}$(date): Backup process completed.${ENDL}"
