#!/usr/bin/env bash

# Source the formatting functions (if applicable)
source "$(dirname "$0")/bash_utilities"

# Function to display help information
show_help() {
  print_title "HELP INFORMATION"
  print_header "Usage: $(basename "$0") [OPTIONS] [DIRECTORY]"
  printf "${BLUE}This script finds and deletes empty directories.${ENDL}"

  print_header "Options:"
  printf "${BOLD_BLUE}  -h, --help${ENDL}     ${BLUE}Display this help message.${ENDL}"
  printf "${BOLD_BLUE}  [DIRECTORY]${ENDL}    ${BLUE}The directory to search for empty directories. If not provided, defaults to the current directory.${ENDL}"
  
  print_header "Examples:"
  printf "${BLUE}  $(basename "$0") /path/to/directory${ENDL}  ${BLUE}Find and delete empty directories in the specified directory.${ENDL}"
  printf "${BLUE}  $(basename "$0")${ENDL}                     ${BLUE}Find and delete empty directories in the current directory.${ENDL}"
  exit 0
}


# Parse command line options
while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
  case $1 in
    -h | --help )
      show_help
      ;;
    * )
      printf "${RED}Invalid option: $1${ENDL}" 1>&2
      show_help
      ;;
  esac
  shift
done

# Set the target directory
if [ -n "$1" ]; then
  target_dir="$1"
else
  target_dir="."
fi

# Check if the provided target is a directory
if [ ! -d "$target_dir" ]; then
  printf "${RED}Error: $target_dir is not a valid directory.${ENDL}"
  exit 1
fi

# Begin operation
print_title "BEGIN EMPTY DIRECTORY DELETION"

# Find empty directories in the target directory recursively
print_header "Finding Empty Directories in $target_dir"
empty_dirs=$(find "$target_dir" -type d -empty)

# Output each empty directory before deletion
if [ -n "$empty_dirs" ]; then
  printf "${BLUE}The following empty directories will be deleted:${ENDL}"
  echo "$empty_dirs"
  
  # Ask for confirmation before deletion
  if confirm_action "Do you want to proceed with deletion? (y/n)"; then
    # Delete the empty directories
    find "$target_dir" -type d -empty -delete
    printf "${GREEN}Empty directories have been deleted.${ENDL}"
  else
    printf "${YELLOW}Deletion canceled.${ENDL}"
  fi
else
  echo "No empty directories found in $target_dir."
fi

# End operation
print_title "EMPTY DIRECTORY DELETION COMPLETE"
echo "Directory: file//:$target_dir"
